[build]
command = "npm run build"
publish = ".next"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/*"
[headers.values]
Permissions-Policy = "geolocation=(), microphone=(), camera=()"
Referrer-Policy = "no-referrer-when-downgrade"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.clthub.com.pl https://<TUNNEL_HOST>; frame-src https://<TUNNEL_HOST>;"
