[[headers]]
for = "/*"
  [headers.values]
  # CSP dostosowane do Next.js (można potem zacieśnić z nonce/hash)
  Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' https:; frame-src 'self' https:; worker-src 'self' blob:; base-uri 'self'; form-action 'self'"
  Referrer-Policy = "no-referrer-when-downgrade"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
